-- Human-readable migration record for MISSING DB INDEX (perf HIGH #2) on
-- conversations. The inbox query is
--   WHERE participant_a = $me OR participant_b = $me
-- participant_a is already covered by the LEFTMOST prefix of the composite
-- UNIQUE (participant_a, participant_b), so that OR-branch can index-scan. The
-- participant_b branch had NO usable index and fell back to a seq scan, so the
-- whole OR degraded to a seq scan of conversations on every inbox load.
--
-- NOTE: This file documents the schema delta only. The live apply happens via
-- the owner-gated `prisma db push` on service restart (mirroring the F31
-- sleep-service 20260621_health_samples migration-record precedent). db push
-- reads the new @@index([participantB]) from schema.prisma and issues a plain
-- CREATE INDEX in lockstep; this DDL documents that delta. It is NOT run by
-- `prisma migrate deploy`.
--
-- SAFETY: this only CREATES an index. No table is altered and no row is touched,
-- so the apply is data-loss-free. Query results are byte-identical before and
-- after — only the access path (and latency) changes.
--
-- LARGE-TABLE NOTE: `prisma db push` emits a PLAIN `CREATE INDEX`, which takes a
-- SHARE lock and blocks concurrent writes to conversations while it builds. On a
-- small/empty table that is instant. On a large existing table the owner may
-- prefer to apply the equivalent `CREATE INDEX CONCURRENTLY` out-of-band (it
-- cannot run inside a transaction and is not what db push emits) and then let
-- db push see the index already present as a no-op.
CREATE INDEX "conversations_participant_b_idx"
    ON "conversations"("participant_b");

-- Equivalent non-blocking form for a large existing table (run manually; not
-- emitted by db push):
--   CREATE INDEX CONCURRENTLY "conversations_participant_b_idx"
--       ON "conversations"("participant_b");
