import { PrismaClient } from './generated/prisma';

const prisma = new PrismaClient();

/**
 * Seed-recipe record shape.
 *
 * Mirrors the `POST /v1/meals/recipes` create body (see routes.ts `createRecipe`)
 * and the Prisma `Recipe` model: each ingredient is `{ name, amount, unit? }`
 * (amount is a STRING — e.g. "1/4", "200" — exactly as the route's Zod schema
 * declares), instructions are ordered strings, and `image` is a URL. The seeder
 * spreads each record straight into `prisma.recipe.create`, so every key here is
 * a valid `Recipe` column and nothing extra leaks into the DB write.
 *
 * `tags` carries BOTH the discoverability chips the mobile Recipes screen filters
 * on — 'High Protein' | 'Keto' | 'Vegan' | 'Meal Prep' | 'Under 30m' — AND the
 * meal-type bucket — 'Breakfast' | 'Lunch' | 'Dinner' | 'Snack' — encoded the
 * same free-form way the original seed set did.
 */
type SeedIngredient = { name: string; amount: string; unit?: string };
type SeedRecipe = {
    title: string;
    description: string;
    image: string;
    prepTimeMins: number;
    cookTimeMins: number;
    servings: number;
    calories: number;
    protein: number;
    carbs: number;
    fat: number;
    tags: string[];
    ingredients: SeedIngredient[];
    instructions: string[];
};

export const MOCK_RECIPES: SeedRecipe[] = [
    {
        title: 'High-Protein Chicken Quinoa Bowl',
        description: 'A quick, macro-friendly meal prep staple packed with lean protein and complex carbs.',
        image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&q=80',
        prepTimeMins: 25,
        cookTimeMins: 0,
        servings: 1,
        calories: 520,
        protein: 45,
        carbs: 55,
        fat: 12,
        tags: ['High Protein', 'Meal Prep', 'Lunch'],
        ingredients: [
            { name: 'Chicken Breast', amount: '200', unit: 'g' },
            { name: 'Quinoa (cooked)', amount: '100', unit: 'g' },
            { name: 'Cherry Tomatoes', amount: '50', unit: 'g' },
            { name: 'Avocado', amount: '1/4' },
            { name: 'Olive Oil', amount: '1', unit: 'tbsp' },
            { name: 'Lemon', amount: '1', unit: 'squeeze' },
        ],
        instructions: [
            'Season chicken breast with salt, pepper, and paprika.',
            'Grill or pan-fry the chicken for 6-8 minutes per side until fully cooked.',
            'While chicken cooks, prepare quinoa according to package instructions.',
            'Dice tomatoes and slice avocado.',
            'Combine quinoa, chicken, and veggies in a bowl. Drizzle with olive oil and lemon.',
        ],
    },
    {
        title: 'Post-Workout Berry Smoothie',
        description: 'Fast-digesting carbs and whey isolate for optimal recovery after heavy lifting.',
        image: 'https://images.unsplash.com/photo-1628557044797-f21a177c37ec?w=800&q=80',
        prepTimeMins: 5,
        cookTimeMins: 0,
        servings: 1,
        calories: 340,
        protein: 30,
        carbs: 45,
        fat: 5,
        tags: ['High Protein', 'Breakfast', 'Under 30m'],
        ingredients: [
            { name: 'Whey Protein Isolate', amount: '1', unit: 'scoop' },
            { name: 'Mixed Frozen Berries', amount: '1', unit: 'cup' },
            { name: 'Banana', amount: '1/2' },
            { name: 'Almond Milk', amount: '1', unit: 'cup' },
            { name: 'Honey', amount: '1', unit: 'tbsp' },
        ],
        instructions: [
            'Add almond milk to the blender first.',
            'Add the whey protein, followed by the frozen berries and banana.',
            'Drizzle in the honey.',
            'Blend on high for 45-60 seconds until smooth.',
        ],
    },
    {
        title: 'Lean Steak & Sweet Potato Mash',
        description: 'A hearty, nutrient-dense dinner perfect for building mass.',
        image: 'https://images.unsplash.com/photo-1554160454-e74f85e43444?w=800&q=80',
        prepTimeMins: 15,
        cookTimeMins: 20,
        servings: 2,
        calories: 680,
        protein: 55,
        carbs: 60,
        fat: 22,
        tags: ['Dinner', 'High Protein'],
        ingredients: [
            { name: 'Sirloin Steak (trimmed)', amount: '250', unit: 'g' },
            { name: 'Sweet Potato', amount: '200', unit: 'g' },
            { name: 'Asparagus', amount: '100', unit: 'g' },
            { name: 'Grass-fed Butter', amount: '1', unit: 'tbsp' },
            { name: 'Garlic & Rosemary', amount: 'to taste' },
        ],
        instructions: [
            'Peel and dice sweet potato. Boil for 15-20 mins until fork-tender.',
            'Season steak aggressively with salt and pepper.',
            'Heat a cast-iron skillet on high. Sear steak for 3-4 mins per side for medium-rare.',
            'Add butter, garlic, and rosemary to the pan, basting the steak for 1 minute.',
            'Rest steak for 5 minutes. Mash the sweet potato and quickly char the asparagus.',
        ],
    },
    {
        title: 'Greek Yogurt Protein Pancakes',
        description: 'Fluffy high-protein pancakes that taste like a cheat meal but fit your macros.',
        image: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800&q=80',
        prepTimeMins: 10,
        cookTimeMins: 10,
        servings: 1,
        calories: 410,
        protein: 38,
        carbs: 42,
        fat: 9,
        tags: ['High Protein', 'Breakfast', 'Under 30m'],
        ingredients: [
            { name: 'Greek Yogurt', amount: '150', unit: 'g' },
            { name: 'Oat Flour', amount: '60', unit: 'g' },
            { name: 'Egg', amount: '1' },
            { name: 'Vanilla Whey Protein', amount: '1/2', unit: 'scoop' },
            { name: 'Baking Powder', amount: '1', unit: 'tsp' },
            { name: 'Mixed Berries', amount: '50', unit: 'g' },
        ],
        instructions: [
            'Whisk yogurt, egg, oat flour, whey, and baking powder into a thick batter.',
            'Heat a non-stick pan over medium and lightly grease it.',
            'Pour small rounds of batter and cook 2-3 minutes until bubbles form.',
            'Flip and cook another 1-2 minutes until golden.',
            'Stack and top with fresh mixed berries.',
        ],
    },
    {
        title: 'Keto Bacon & Avocado Egg Cups',
        description: 'Zero-carb, fat-forward breakfast cups you can bake ahead for the week.',
        image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=800&q=80',
        prepTimeMins: 10,
        cookTimeMins: 18,
        servings: 4,
        calories: 290,
        protein: 18,
        carbs: 3,
        fat: 23,
        tags: ['Keto', 'Breakfast', 'Meal Prep'],
        ingredients: [
            { name: 'Eggs', amount: '6' },
            { name: 'Bacon', amount: '4', unit: 'slices' },
            { name: 'Avocado', amount: '1' },
            { name: 'Cheddar Cheese', amount: '40', unit: 'g' },
            { name: 'Chives', amount: '1', unit: 'tbsp' },
        ],
        instructions: [
            'Preheat oven to 190C (375F) and line a muffin tin.',
            'Lay half a bacon slice into each cup to form a base.',
            'Whisk eggs with salt and pepper, then pour into the cups.',
            'Top with diced avocado and shredded cheddar.',
            'Bake 16-18 minutes until set. Garnish with chives.',
        ],
    },
    {
        title: 'Vegan Tofu Scramble Wrap',
        description: 'A savory plant-based breakfast wrap with turmeric tofu and black beans.',
        image: 'https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=800&q=80',
        prepTimeMins: 10,
        cookTimeMins: 12,
        servings: 2,
        calories: 430,
        protein: 24,
        carbs: 48,
        fat: 16,
        tags: ['Vegan', 'Breakfast', 'Under 30m'],
        ingredients: [
            { name: 'Firm Tofu', amount: '200', unit: 'g' },
            { name: 'Black Beans', amount: '100', unit: 'g' },
            { name: 'Whole-Wheat Tortillas', amount: '2' },
            { name: 'Turmeric', amount: '1/2', unit: 'tsp' },
            { name: 'Spinach', amount: '50', unit: 'g' },
            { name: 'Olive Oil', amount: '1', unit: 'tbsp' },
        ],
        instructions: [
            'Crumble the tofu and toss with turmeric, salt, and pepper.',
            'Heat olive oil in a pan and scramble the tofu for 5-6 minutes.',
            'Add black beans and spinach; cook until the spinach wilts.',
            'Warm the tortillas briefly in a dry pan.',
            'Divide the scramble between tortillas, roll tightly, and serve.',
        ],
    },
    {
        title: 'Overnight Protein Oats',
        description: 'Prep-ahead jars of creamy oats with whey and chia for a grab-and-go breakfast.',
        image: 'https://images.unsplash.com/photo-1517673400267-0251440c45dc?w=800&q=80',
        prepTimeMins: 8,
        cookTimeMins: 0,
        servings: 1,
        calories: 450,
        protein: 32,
        carbs: 55,
        fat: 11,
        tags: ['High Protein', 'Breakfast', 'Meal Prep'],
        ingredients: [
            { name: 'Rolled Oats', amount: '60', unit: 'g' },
            { name: 'Vanilla Whey Protein', amount: '1', unit: 'scoop' },
            { name: 'Chia Seeds', amount: '1', unit: 'tbsp' },
            { name: 'Milk', amount: '200', unit: 'ml' },
            { name: 'Banana', amount: '1/2' },
            { name: 'Peanut Butter', amount: '1', unit: 'tsp' },
        ],
        instructions: [
            'Stir oats, whey, and chia seeds together in a jar.',
            'Pour in the milk and mix until there are no dry pockets.',
            'Slice the banana over the top and add a swirl of peanut butter.',
            'Seal and refrigerate overnight (at least 6 hours).',
            'Stir and eat cold, or warm briefly if preferred.',
        ],
    },
    {
        title: 'Smashed Avocado Toast with Eggs',
        description: 'A balanced breakfast of sourdough, creamy avocado, and soft-poached eggs.',
        image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=800&q=80',
        prepTimeMins: 8,
        cookTimeMins: 6,
        servings: 1,
        calories: 380,
        protein: 19,
        carbs: 34,
        fat: 20,
        tags: ['Breakfast', 'Under 30m'],
        ingredients: [
            { name: 'Sourdough Bread', amount: '2', unit: 'slices' },
            { name: 'Avocado', amount: '1' },
            { name: 'Eggs', amount: '2' },
            { name: 'Chili Flakes', amount: '1/4', unit: 'tsp' },
            { name: 'Lemon Juice', amount: '1', unit: 'tsp' },
        ],
        instructions: [
            'Toast the sourdough until golden and crisp.',
            'Mash the avocado with lemon juice, salt, and pepper.',
            'Poach the eggs in simmering water for 3 minutes.',
            'Spread the avocado over the toast and top with the poached eggs.',
            'Finish with a pinch of chili flakes.',
        ],
    },
    {
        title: 'Turkey & Brown Rice Meal-Prep Bowls',
        description: 'Five days of lean ground turkey, brown rice, and roasted veg in one tray.',
        image: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=800&q=80',
        prepTimeMins: 15,
        cookTimeMins: 30,
        servings: 5,
        calories: 540,
        protein: 42,
        carbs: 58,
        fat: 14,
        tags: ['High Protein', 'Meal Prep', 'Lunch'],
        ingredients: [
            { name: 'Lean Ground Turkey', amount: '600', unit: 'g' },
            { name: 'Brown Rice (dry)', amount: '300', unit: 'g' },
            { name: 'Broccoli Florets', amount: '300', unit: 'g' },
            { name: 'Bell Peppers', amount: '2' },
            { name: 'Soy Sauce', amount: '3', unit: 'tbsp' },
            { name: 'Olive Oil', amount: '2', unit: 'tbsp' },
        ],
        instructions: [
            'Cook the brown rice according to package directions.',
            'Brown the turkey in a large pan with olive oil, breaking it up as it cooks.',
            'Add chopped peppers and soy sauce; cook 5 more minutes.',
            'Roast the broccoli at 200C (400F) for 18-20 minutes.',
            'Divide rice, turkey, and broccoli across five containers and refrigerate.',
        ],
    },
    {
        title: 'Keto Cobb Salad',
        description: 'A loaded low-carb salad with chicken, egg, bacon, and blue cheese.',
        image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80',
        prepTimeMins: 20,
        cookTimeMins: 0,
        servings: 2,
        calories: 560,
        protein: 40,
        carbs: 8,
        fat: 40,
        tags: ['Keto', 'Lunch', 'High Protein'],
        ingredients: [
            { name: 'Cooked Chicken Breast', amount: '200', unit: 'g' },
            { name: 'Hard-Boiled Eggs', amount: '2' },
            { name: 'Bacon', amount: '3', unit: 'slices' },
            { name: 'Avocado', amount: '1' },
            { name: 'Blue Cheese', amount: '40', unit: 'g' },
            { name: 'Romaine Lettuce', amount: '150', unit: 'g' },
        ],
        instructions: [
            'Chop the romaine and spread it across a wide bowl.',
            'Cook the bacon until crisp, then crumble it.',
            'Slice the chicken, eggs, and avocado.',
            'Arrange chicken, eggs, bacon, and avocado in rows over the lettuce.',
            'Crumble blue cheese on top and dress with olive oil and vinegar.',
        ],
    },
    {
        title: 'Vegan Buddha Bowl',
        description: 'A colorful plant bowl of chickpeas, roasted sweet potato, and tahini drizzle.',
        image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80',
        prepTimeMins: 15,
        cookTimeMins: 25,
        servings: 2,
        calories: 520,
        protein: 19,
        carbs: 72,
        fat: 18,
        tags: ['Vegan', 'Lunch', 'Meal Prep'],
        ingredients: [
            { name: 'Chickpeas', amount: '240', unit: 'g' },
            { name: 'Sweet Potato', amount: '250', unit: 'g' },
            { name: 'Quinoa (dry)', amount: '120', unit: 'g' },
            { name: 'Kale', amount: '80', unit: 'g' },
            { name: 'Tahini', amount: '2', unit: 'tbsp' },
            { name: 'Lemon Juice', amount: '1', unit: 'tbsp' },
        ],
        instructions: [
            'Roast cubed sweet potato and chickpeas at 200C (400F) for 25 minutes.',
            'Cook quinoa according to package directions.',
            'Massage the kale with a little olive oil and salt.',
            'Whisk tahini with lemon juice and a splash of water into a pourable sauce.',
            'Assemble bowls with quinoa, veg, and chickpeas, then drizzle with tahini.',
        ],
    },
    {
        title: 'Grilled Chicken Caesar Wrap',
        description: 'A quick lunch wrap with grilled chicken, romaine, and a light Caesar dressing.',
        image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=800&q=80',
        prepTimeMins: 12,
        cookTimeMins: 10,
        servings: 1,
        calories: 480,
        protein: 41,
        carbs: 38,
        fat: 18,
        tags: ['High Protein', 'Lunch', 'Under 30m'],
        ingredients: [
            { name: 'Chicken Breast', amount: '180', unit: 'g' },
            { name: 'Whole-Wheat Tortilla', amount: '1' },
            { name: 'Romaine Lettuce', amount: '60', unit: 'g' },
            { name: 'Parmesan', amount: '20', unit: 'g' },
            { name: 'Light Caesar Dressing', amount: '2', unit: 'tbsp' },
        ],
        instructions: [
            'Season and grill the chicken for 6-7 minutes per side, then slice.',
            'Toss the romaine with Caesar dressing and parmesan.',
            'Warm the tortilla briefly to make it pliable.',
            'Layer the chicken and dressed lettuce down the center.',
            'Fold in the sides and roll tightly, then slice in half.',
        ],
    },
    {
        title: 'Spicy Tuna Poke Bowl',
        description: 'Fresh ahi tuna over rice with edamame, cucumber, and a spicy mayo drizzle.',
        image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&q=80',
        prepTimeMins: 20,
        cookTimeMins: 0,
        servings: 1,
        calories: 560,
        protein: 40,
        carbs: 60,
        fat: 16,
        tags: ['High Protein', 'Lunch'],
        ingredients: [
            { name: 'Sushi-Grade Tuna', amount: '150', unit: 'g' },
            { name: 'Sushi Rice (cooked)', amount: '200', unit: 'g' },
            { name: 'Edamame', amount: '60', unit: 'g' },
            { name: 'Cucumber', amount: '1/2' },
            { name: 'Soy Sauce', amount: '2', unit: 'tbsp' },
            { name: 'Spicy Mayo', amount: '1', unit: 'tbsp' },
        ],
        instructions: [
            'Dice the tuna into bite-sized cubes and toss with soy sauce.',
            'Spoon the rice into a bowl as the base.',
            'Arrange tuna, edamame, and sliced cucumber over the rice.',
            'Drizzle with spicy mayo.',
            'Garnish with sesame seeds and serve immediately.',
        ],
    },
    {
        title: 'Mediterranean Quinoa Salad',
        description: 'A make-ahead vegan salad with cucumber, tomato, olives, and lemon dressing.',
        image: 'https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?w=800&q=80',
        prepTimeMins: 18,
        cookTimeMins: 15,
        servings: 4,
        calories: 360,
        protein: 12,
        carbs: 52,
        fat: 13,
        tags: ['Vegan', 'Lunch', 'Meal Prep'],
        ingredients: [
            { name: 'Quinoa (dry)', amount: '200', unit: 'g' },
            { name: 'Cucumber', amount: '1' },
            { name: 'Cherry Tomatoes', amount: '150', unit: 'g' },
            { name: 'Kalamata Olives', amount: '60', unit: 'g' },
            { name: 'Red Onion', amount: '1/2' },
            { name: 'Olive Oil', amount: '3', unit: 'tbsp' },
        ],
        instructions: [
            'Cook the quinoa and let it cool to room temperature.',
            'Dice the cucumber, tomatoes, and red onion.',
            'Combine the quinoa and vegetables with the olives.',
            'Whisk olive oil with lemon juice, salt, and pepper.',
            'Toss everything together and chill before serving.',
        ],
    },
    {
        title: 'Beef & Broccoli Stir-Fry',
        description: 'A fast weeknight stir-fry with tender beef strips in a savory garlic sauce.',
        image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80',
        prepTimeMins: 15,
        cookTimeMins: 12,
        servings: 3,
        calories: 510,
        protein: 38,
        carbs: 40,
        fat: 20,
        tags: ['High Protein', 'Dinner', 'Under 30m'],
        ingredients: [
            { name: 'Flank Steak', amount: '400', unit: 'g' },
            { name: 'Broccoli Florets', amount: '300', unit: 'g' },
            { name: 'Garlic', amount: '3', unit: 'cloves' },
            { name: 'Soy Sauce', amount: '4', unit: 'tbsp' },
            { name: 'Cornstarch', amount: '1', unit: 'tbsp' },
            { name: 'Cooked Rice', amount: '450', unit: 'g' },
        ],
        instructions: [
            'Slice the steak thinly against the grain and toss with cornstarch.',
            'Sear the beef in a hot wok for 2-3 minutes, then set aside.',
            'Stir-fry the broccoli and garlic for 4-5 minutes.',
            'Return the beef, add soy sauce, and toss until glossy.',
            'Serve over cooked rice.',
        ],
    },
    {
        title: 'Keto Salmon with Asparagus',
        description: 'Pan-seared salmon and buttery asparagus — a clean, low-carb dinner in 20 minutes.',
        image: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800&q=80',
        prepTimeMins: 8,
        cookTimeMins: 14,
        servings: 2,
        calories: 520,
        protein: 42,
        carbs: 6,
        fat: 36,
        tags: ['Keto', 'Dinner', 'High Protein'],
        ingredients: [
            { name: 'Salmon Fillets', amount: '2' },
            { name: 'Asparagus', amount: '200', unit: 'g' },
            { name: 'Butter', amount: '2', unit: 'tbsp' },
            { name: 'Garlic', amount: '2', unit: 'cloves' },
            { name: 'Lemon', amount: '1' },
        ],
        instructions: [
            'Pat the salmon dry and season with salt and pepper.',
            'Sear skin-side down in a hot pan for 4-5 minutes, then flip for 2-3 more.',
            'Remove the salmon and add butter and garlic to the pan.',
            'Toss the asparagus in the garlic butter for 4-5 minutes.',
            'Plate together and finish with a squeeze of lemon.',
        ],
    },
    {
        title: 'Vegan Chickpea Curry',
        description: 'A creamy coconut chickpea curry that freezes beautifully for meal prep.',
        image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=800&q=80',
        prepTimeMins: 12,
        cookTimeMins: 25,
        servings: 4,
        calories: 470,
        protein: 16,
        carbs: 62,
        fat: 18,
        tags: ['Vegan', 'Dinner', 'Meal Prep'],
        ingredients: [
            { name: 'Chickpeas', amount: '480', unit: 'g' },
            { name: 'Coconut Milk', amount: '400', unit: 'ml' },
            { name: 'Diced Tomatoes', amount: '400', unit: 'g' },
            { name: 'Onion', amount: '1' },
            { name: 'Curry Powder', amount: '2', unit: 'tbsp' },
            { name: 'Basmati Rice (dry)', amount: '200', unit: 'g' },
        ],
        instructions: [
            'Saute the diced onion until soft and translucent.',
            'Stir in the curry powder and cook for 1 minute until fragrant.',
            'Add the tomatoes, chickpeas, and coconut milk.',
            'Simmer for 20 minutes until thickened.',
            'Serve over cooked basmati rice.',
        ],
    },
    {
        title: 'Sheet-Pan Lemon Herb Chicken & Veg',
        description: 'Everything roasts on one tray — juicy chicken thighs with potatoes and green beans.',
        image: 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?w=800&q=80',
        prepTimeMins: 15,
        cookTimeMins: 35,
        servings: 4,
        calories: 580,
        protein: 44,
        carbs: 45,
        fat: 24,
        tags: ['High Protein', 'Dinner', 'Meal Prep'],
        ingredients: [
            { name: 'Chicken Thighs', amount: '8' },
            { name: 'Baby Potatoes', amount: '500', unit: 'g' },
            { name: 'Green Beans', amount: '250', unit: 'g' },
            { name: 'Lemon', amount: '1' },
            { name: 'Olive Oil', amount: '3', unit: 'tbsp' },
            { name: 'Mixed Herbs', amount: '1', unit: 'tbsp' },
        ],
        instructions: [
            'Preheat oven to 200C (400F).',
            'Toss the potatoes and chicken with olive oil, herbs, salt, and pepper.',
            'Spread on a sheet pan and roast for 20 minutes.',
            'Add the green beans and lemon wedges; roast 15 more minutes.',
            'Rest 5 minutes before serving.',
        ],
    },
    {
        title: 'Shrimp Zucchini Noodle Scampi',
        description: 'A light, low-carb take on scampi with garlic-butter shrimp over zucchini noodles.',
        image: 'https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=800&q=80',
        prepTimeMins: 12,
        cookTimeMins: 10,
        servings: 2,
        calories: 360,
        protein: 35,
        carbs: 12,
        fat: 18,
        tags: ['Keto', 'Dinner', 'Under 30m'],
        ingredients: [
            { name: 'Shrimp (peeled)', amount: '300', unit: 'g' },
            { name: 'Zucchini', amount: '3' },
            { name: 'Butter', amount: '2', unit: 'tbsp' },
            { name: 'Garlic', amount: '3', unit: 'cloves' },
            { name: 'White Wine', amount: '60', unit: 'ml' },
            { name: 'Parsley', amount: '2', unit: 'tbsp' },
        ],
        instructions: [
            'Spiralize the zucchini into noodles and set aside.',
            'Melt butter and saute the garlic for 30 seconds.',
            'Add the shrimp and cook 2-3 minutes until pink.',
            'Pour in the white wine and simmer for 2 minutes.',
            'Toss in the zucchini noodles, warm through, and finish with parsley.',
        ],
    },
    {
        title: 'Turkey Chili',
        description: 'A hearty, high-protein chili that gets better the next day — perfect for batch cooking.',
        image: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800&q=80',
        prepTimeMins: 15,
        cookTimeMins: 40,
        servings: 6,
        calories: 420,
        protein: 36,
        carbs: 38,
        fat: 14,
        tags: ['High Protein', 'Dinner', 'Meal Prep'],
        ingredients: [
            { name: 'Lean Ground Turkey', amount: '700', unit: 'g' },
            { name: 'Kidney Beans', amount: '480', unit: 'g' },
            { name: 'Diced Tomatoes', amount: '800', unit: 'g' },
            { name: 'Onion', amount: '1' },
            { name: 'Chili Powder', amount: '2', unit: 'tbsp' },
            { name: 'Bell Pepper', amount: '1' },
        ],
        instructions: [
            'Brown the turkey with the diced onion in a large pot.',
            'Stir in the chili powder and chopped bell pepper.',
            'Add the tomatoes and beans, then bring to a simmer.',
            'Simmer uncovered for 35-40 minutes, stirring occasionally.',
            'Season to taste and serve, or cool and portion for the week.',
        ],
    },
    {
        title: 'Cottage Cheese & Berry Bowl',
        description: 'A five-minute high-protein snack bowl with cottage cheese, berries, and almonds.',
        image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800&q=80',
        prepTimeMins: 5,
        cookTimeMins: 0,
        servings: 1,
        calories: 250,
        protein: 28,
        carbs: 18,
        fat: 8,
        tags: ['High Protein', 'Snack', 'Under 30m'],
        ingredients: [
            { name: 'Cottage Cheese', amount: '200', unit: 'g' },
            { name: 'Mixed Berries', amount: '80', unit: 'g' },
            { name: 'Almonds', amount: '15', unit: 'g' },
            { name: 'Honey', amount: '1', unit: 'tsp' },
        ],
        instructions: [
            'Spoon the cottage cheese into a bowl.',
            'Top with the mixed berries and chopped almonds.',
            'Drizzle with honey.',
            'Stir gently and enjoy.',
        ],
    },
    {
        title: 'No-Bake Peanut Butter Protein Balls',
        description: 'Bite-sized energy balls with oats, peanut butter, and whey — great for meal prep.',
        image: 'https://images.unsplash.com/photo-1599599810769-bcde5a160d32?w=800&q=80',
        prepTimeMins: 15,
        cookTimeMins: 0,
        servings: 12,
        calories: 140,
        protein: 8,
        carbs: 14,
        fat: 7,
        tags: ['High Protein', 'Snack', 'Meal Prep'],
        ingredients: [
            { name: 'Rolled Oats', amount: '150', unit: 'g' },
            { name: 'Peanut Butter', amount: '120', unit: 'g' },
            { name: 'Vanilla Whey Protein', amount: '2', unit: 'scoops' },
            { name: 'Honey', amount: '3', unit: 'tbsp' },
            { name: 'Dark Chocolate Chips', amount: '40', unit: 'g' },
        ],
        instructions: [
            'Mix the oats, whey, and chocolate chips in a bowl.',
            'Stir in the peanut butter and honey until a sticky dough forms.',
            'Roll the dough into 12 evenly sized balls.',
            'Chill in the fridge for at least 30 minutes to firm up.',
            'Store in an airtight container for up to a week.',
        ],
    },
    {
        title: 'Keto Fat Bombs',
        description: 'Rich coconut and almond butter bites to curb cravings on a low-carb day.',
        image: 'https://images.unsplash.com/photo-1606312619070-d48b4c652a52?w=800&q=80',
        prepTimeMins: 10,
        cookTimeMins: 0,
        servings: 10,
        calories: 160,
        protein: 3,
        carbs: 4,
        fat: 16,
        tags: ['Keto', 'Snack', 'Meal Prep'],
        ingredients: [
            { name: 'Coconut Oil', amount: '120', unit: 'g' },
            { name: 'Almond Butter', amount: '100', unit: 'g' },
            { name: 'Cocoa Powder', amount: '2', unit: 'tbsp' },
            { name: 'Erythritol', amount: '2', unit: 'tbsp' },
            { name: 'Vanilla Extract', amount: '1', unit: 'tsp' },
        ],
        instructions: [
            'Gently melt the coconut oil and almond butter together.',
            'Whisk in the cocoa powder, erythritol, and vanilla.',
            'Pour the mixture into a silicone mold.',
            'Freeze for 30 minutes until solid.',
            'Pop out and keep refrigerated.',
        ],
    },
    {
        title: 'Vegan Hummus & Veggie Plate',
        description: 'A simple, fiber-rich snack plate of homemade hummus with crunchy crudites.',
        image: 'https://images.unsplash.com/photo-1505576633757-0ac1084af824?w=800&q=80',
        prepTimeMins: 12,
        cookTimeMins: 0,
        servings: 2,
        calories: 260,
        protein: 10,
        carbs: 30,
        fat: 12,
        tags: ['Vegan', 'Snack', 'Under 30m'],
        ingredients: [
            { name: 'Chickpeas', amount: '240', unit: 'g' },
            { name: 'Tahini', amount: '2', unit: 'tbsp' },
            { name: 'Lemon Juice', amount: '2', unit: 'tbsp' },
            { name: 'Garlic', amount: '1', unit: 'clove' },
            { name: 'Carrots', amount: '2' },
            { name: 'Cucumber', amount: '1' },
        ],
        instructions: [
            'Blend the chickpeas, tahini, lemon juice, and garlic until smooth.',
            'Loosen the hummus with a little cold water and season with salt.',
            'Cut the carrots and cucumber into sticks.',
            'Spoon the hummus into a bowl and drizzle with olive oil.',
            'Serve with the veggie sticks for dipping.',
        ],
    },
    {
        title: 'Egg White Veggie Omelette',
        description: 'A lean, low-fat breakfast omelette loaded with peppers, spinach, and tomato.',
        image: 'https://images.unsplash.com/photo-1510693206972-df098062cb71?w=800&q=80',
        prepTimeMins: 8,
        cookTimeMins: 8,
        servings: 1,
        calories: 220,
        protein: 26,
        carbs: 10,
        fat: 8,
        tags: ['High Protein', 'Breakfast', 'Under 30m'],
        ingredients: [
            { name: 'Egg Whites', amount: '6' },
            { name: 'Spinach', amount: '40', unit: 'g' },
            { name: 'Bell Pepper', amount: '1/2' },
            { name: 'Cherry Tomatoes', amount: '40', unit: 'g' },
            { name: 'Olive Oil', amount: '1', unit: 'tsp' },
        ],
        instructions: [
            'Whisk the egg whites with salt and pepper.',
            'Saute the diced pepper and tomatoes in olive oil for 2 minutes.',
            'Add the spinach and cook until just wilted.',
            'Pour in the egg whites and cook over low heat until set.',
            'Fold in half and slide onto a plate.',
        ],
    },
    {
        title: 'Pesto Chicken Pasta',
        description: 'A crowd-pleasing dinner of whole-wheat pasta tossed with basil pesto and chicken.',
        image: 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=800&q=80',
        prepTimeMins: 12,
        cookTimeMins: 18,
        servings: 4,
        calories: 620,
        protein: 40,
        carbs: 65,
        fat: 22,
        tags: ['High Protein', 'Dinner'],
        ingredients: [
            { name: 'Whole-Wheat Pasta', amount: '320', unit: 'g' },
            { name: 'Chicken Breast', amount: '400', unit: 'g' },
            { name: 'Basil Pesto', amount: '6', unit: 'tbsp' },
            { name: 'Cherry Tomatoes', amount: '150', unit: 'g' },
            { name: 'Parmesan', amount: '40', unit: 'g' },
        ],
        instructions: [
            'Cook the pasta until al dente and reserve a cup of the cooking water.',
            'Season and grill the chicken, then slice it.',
            'Toss the drained pasta with pesto, loosening with the reserved water.',
            'Fold in the chicken and halved cherry tomatoes.',
            'Top with grated parmesan and serve.',
        ],
    },
    {
        title: 'Black Bean Burrito Bowl',
        description: 'A satisfying vegan bowl of rice, black beans, corn, and zesty lime.',
        image: 'https://images.unsplash.com/photo-1543339308-43e59d6b73a6?w=800&q=80',
        prepTimeMins: 15,
        cookTimeMins: 15,
        servings: 3,
        calories: 490,
        protein: 18,
        carbs: 78,
        fat: 12,
        tags: ['Vegan', 'Lunch', 'Meal Prep'],
        ingredients: [
            { name: 'Black Beans', amount: '360', unit: 'g' },
            { name: 'Brown Rice (dry)', amount: '200', unit: 'g' },
            { name: 'Corn', amount: '150', unit: 'g' },
            { name: 'Avocado', amount: '1' },
            { name: 'Lime', amount: '1' },
            { name: 'Salsa', amount: '100', unit: 'g' },
        ],
        instructions: [
            'Cook the brown rice and fluff with lime juice and salt.',
            'Warm the black beans with a pinch of cumin.',
            'Char the corn briefly in a dry pan.',
            'Build bowls with rice, beans, and corn.',
            'Top with sliced avocado and salsa.',
        ],
    },
    {
        title: 'Garlic Butter Steak Bites',
        description: 'Quick-seared sirloin cubes in garlic butter — a low-carb dinner ready in 20 minutes.',
        image: 'https://images.unsplash.com/photo-1600891964092-4316c288032e?w=800&q=80',
        prepTimeMins: 10,
        cookTimeMins: 10,
        servings: 2,
        calories: 540,
        protein: 46,
        carbs: 4,
        fat: 38,
        tags: ['Keto', 'Dinner', 'High Protein'],
        ingredients: [
            { name: 'Sirloin Steak', amount: '400', unit: 'g' },
            { name: 'Butter', amount: '3', unit: 'tbsp' },
            { name: 'Garlic', amount: '4', unit: 'cloves' },
            { name: 'Fresh Thyme', amount: '1', unit: 'tbsp' },
        ],
        instructions: [
            'Cut the steak into bite-sized cubes and pat dry.',
            'Sear the cubes in a screaming-hot pan for 1-2 minutes per side.',
            'Lower the heat and add butter, garlic, and thyme.',
            'Spoon the garlic butter over the steak for 1 minute.',
            'Rest briefly and serve.',
        ],
    },
    {
        title: 'Banana Oat Protein Muffins',
        description: 'Flourless banana muffins blended with oats and whey — a perfect prep-ahead snack.',
        image: 'https://images.unsplash.com/photo-1607958996333-41aef7caefaa?w=800&q=80',
        prepTimeMins: 12,
        cookTimeMins: 20,
        servings: 9,
        calories: 180,
        protein: 11,
        carbs: 26,
        fat: 4,
        tags: ['High Protein', 'Snack', 'Meal Prep'],
        ingredients: [
            { name: 'Ripe Bananas', amount: '3' },
            { name: 'Rolled Oats', amount: '180', unit: 'g' },
            { name: 'Eggs', amount: '2' },
            { name: 'Vanilla Whey Protein', amount: '2', unit: 'scoops' },
            { name: 'Baking Powder', amount: '1', unit: 'tsp' },
        ],
        instructions: [
            'Preheat oven to 180C (350F) and line a muffin tin.',
            'Blend the bananas, oats, eggs, whey, and baking powder until smooth.',
            'Divide the batter across nine muffin cups.',
            'Bake for 18-20 minutes until a toothpick comes out clean.',
            'Cool before storing in an airtight container.',
        ],
    },
    {
        title: 'Tuna & White Bean Salad',
        description: 'A protein-packed no-cook lunch with tuna, cannellini beans, and lemon.',
        image: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=800&q=80',
        prepTimeMins: 10,
        cookTimeMins: 0,
        servings: 2,
        calories: 380,
        protein: 34,
        carbs: 32,
        fat: 12,
        tags: ['High Protein', 'Lunch', 'Under 30m'],
        ingredients: [
            { name: 'Canned Tuna', amount: '160', unit: 'g' },
            { name: 'Cannellini Beans', amount: '240', unit: 'g' },
            { name: 'Red Onion', amount: '1/4' },
            { name: 'Parsley', amount: '2', unit: 'tbsp' },
            { name: 'Olive Oil', amount: '2', unit: 'tbsp' },
            { name: 'Lemon Juice', amount: '1', unit: 'tbsp' },
        ],
        instructions: [
            'Drain the tuna and beans well.',
            'Finely slice the red onion and chop the parsley.',
            'Combine the tuna, beans, onion, and parsley in a bowl.',
            'Dress with olive oil, lemon juice, salt, and pepper.',
            'Toss gently and serve.',
        ],
    },
    {
        title: 'Vegan Lentil Bolognese',
        description: 'A rich, meaty-tasting lentil ragu over spaghetti — freezer-friendly and filling.',
        image: 'https://images.unsplash.com/photo-1551892374-ecf8754cf8b0?w=800&q=80',
        prepTimeMins: 15,
        cookTimeMins: 35,
        servings: 4,
        calories: 520,
        protein: 22,
        carbs: 88,
        fat: 9,
        tags: ['Vegan', 'Dinner', 'Meal Prep'],
        ingredients: [
            { name: 'Brown Lentils (dry)', amount: '200', unit: 'g' },
            { name: 'Crushed Tomatoes', amount: '700', unit: 'g' },
            { name: 'Onion', amount: '1' },
            { name: 'Carrot', amount: '1' },
            { name: 'Spaghetti', amount: '320', unit: 'g' },
            { name: 'Garlic', amount: '2', unit: 'cloves' },
        ],
        instructions: [
            'Saute the diced onion, carrot, and garlic until soft.',
            'Add the lentils and crushed tomatoes with a cup of water.',
            'Simmer for 30 minutes until the lentils are tender.',
            'Cook the spaghetti until al dente.',
            'Toss the pasta with the lentil ragu and serve.',
        ],
    },
    {
        title: 'Baked Cod with Herb Crust',
        description: 'Flaky baked cod under a crisp herb-and-breadcrumb crust with a side of greens.',
        image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800&q=80',
        prepTimeMins: 12,
        cookTimeMins: 18,
        servings: 2,
        calories: 360,
        protein: 40,
        carbs: 22,
        fat: 12,
        tags: ['High Protein', 'Dinner'],
        ingredients: [
            { name: 'Cod Fillets', amount: '2' },
            { name: 'Breadcrumbs', amount: '60', unit: 'g' },
            { name: 'Parsley', amount: '2', unit: 'tbsp' },
            { name: 'Lemon Zest', amount: '1', unit: 'tsp' },
            { name: 'Olive Oil', amount: '2', unit: 'tbsp' },
            { name: 'Green Beans', amount: '200', unit: 'g' },
        ],
        instructions: [
            'Preheat oven to 200C (400F).',
            'Mix breadcrumbs, parsley, lemon zest, and olive oil.',
            'Press the crust onto the cod fillets and place on a lined tray.',
            'Bake for 16-18 minutes until the fish flakes easily.',
            'Steam the green beans and serve alongside.',
        ],
    },
    {
        title: 'Protein Iced Coffee Shake',
        description: 'A refreshing 3-minute shake that doubles as a snack and a caffeine hit.',
        image: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800&q=80',
        prepTimeMins: 3,
        cookTimeMins: 0,
        servings: 1,
        calories: 200,
        protein: 27,
        carbs: 12,
        fat: 4,
        tags: ['High Protein', 'Snack', 'Under 30m'],
        ingredients: [
            { name: 'Cold Brew Coffee', amount: '200', unit: 'ml' },
            { name: 'Chocolate Whey Protein', amount: '1', unit: 'scoop' },
            { name: 'Milk', amount: '100', unit: 'ml' },
            { name: 'Ice Cubes', amount: '1', unit: 'cup' },
        ],
        instructions: [
            'Add the cold brew, milk, and protein to a blender.',
            'Drop in the ice cubes.',
            'Blend on high for 30 seconds until frothy.',
            'Pour into a tall glass and serve immediately.',
        ],
    },
    {
        title: 'Stuffed Bell Peppers',
        description: 'Ground beef and rice baked inside sweet bell peppers — a comforting batch dinner.',
        image: 'https://images.unsplash.com/photo-1606787366850-de6330128bfc?w=800&q=80',
        prepTimeMins: 20,
        cookTimeMins: 35,
        servings: 4,
        calories: 460,
        protein: 32,
        carbs: 42,
        fat: 18,
        tags: ['High Protein', 'Dinner', 'Meal Prep'],
        ingredients: [
            { name: 'Bell Peppers', amount: '4' },
            { name: 'Lean Ground Beef', amount: '400', unit: 'g' },
            { name: 'Cooked Rice', amount: '300', unit: 'g' },
            { name: 'Tomato Sauce', amount: '200', unit: 'g' },
            { name: 'Onion', amount: '1' },
            { name: 'Mozzarella', amount: '60', unit: 'g' },
        ],
        instructions: [
            'Preheat oven to 190C (375F) and halve the peppers.',
            'Brown the beef with the diced onion.',
            'Stir in the cooked rice and half the tomato sauce.',
            'Fill the peppers, top with the remaining sauce and mozzarella.',
            'Bake for 30-35 minutes until the peppers are tender.',
        ],
    },
    {
        title: 'Apple Almond Butter Snack Plate',
        description: 'Crisp apple slices with almond butter and a sprinkle of cinnamon — ready in minutes.',
        image: 'https://images.unsplash.com/photo-1568909218985-d0b2f6df9faa?w=800&q=80',
        prepTimeMins: 5,
        cookTimeMins: 0,
        servings: 1,
        calories: 230,
        protein: 7,
        carbs: 28,
        fat: 12,
        tags: ['Vegan', 'Snack', 'Under 30m'],
        ingredients: [
            { name: 'Apple', amount: '1' },
            { name: 'Almond Butter', amount: '2', unit: 'tbsp' },
            { name: 'Cinnamon', amount: '1/4', unit: 'tsp' },
        ],
        instructions: [
            'Core and slice the apple into wedges.',
            'Arrange the wedges on a plate.',
            'Serve with almond butter for dipping.',
            'Dust with cinnamon.',
        ],
    },
    {
        title: 'Keto Cauliflower Fried Rice',
        description: 'A low-carb fried rice swap using riced cauliflower, egg, and sesame.',
        image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80',
        prepTimeMins: 12,
        cookTimeMins: 12,
        servings: 3,
        calories: 280,
        protein: 16,
        carbs: 14,
        fat: 18,
        tags: ['Keto', 'Dinner', 'Under 30m'],
        ingredients: [
            { name: 'Riced Cauliflower', amount: '400', unit: 'g' },
            { name: 'Eggs', amount: '3' },
            { name: 'Peas & Carrots', amount: '120', unit: 'g' },
            { name: 'Soy Sauce', amount: '3', unit: 'tbsp' },
            { name: 'Sesame Oil', amount: '1', unit: 'tbsp' },
            { name: 'Green Onion', amount: '2' },
        ],
        instructions: [
            'Scramble the eggs in a hot wok and set aside.',
            'Stir-fry the peas and carrots for 3 minutes.',
            'Add the riced cauliflower and cook for 5 minutes.',
            'Return the eggs, then add soy sauce and sesame oil.',
            'Toss with sliced green onion and serve.',
        ],
    },
    {
        title: 'Salmon & Quinoa Meal-Prep Boxes',
        description: 'Baked salmon, fluffy quinoa, and roasted veg portioned for four ready-to-eat lunches.',
        image: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800&q=80',
        prepTimeMins: 15,
        cookTimeMins: 25,
        servings: 4,
        calories: 560,
        protein: 42,
        carbs: 48,
        fat: 22,
        tags: ['High Protein', 'Meal Prep', 'Lunch'],
        ingredients: [
            { name: 'Salmon Fillets', amount: '4' },
            { name: 'Quinoa (dry)', amount: '200', unit: 'g' },
            { name: 'Broccoli Florets', amount: '300', unit: 'g' },
            { name: 'Cherry Tomatoes', amount: '200', unit: 'g' },
            { name: 'Olive Oil', amount: '3', unit: 'tbsp' },
            { name: 'Lemon', amount: '1' },
        ],
        instructions: [
            'Cook the quinoa according to package directions.',
            'Roast the salmon and broccoli at 200C (400F) for 18-20 minutes.',
            'Halve the cherry tomatoes and toss with olive oil.',
            'Portion quinoa, salmon, broccoli, and tomatoes into four boxes.',
            'Squeeze lemon over each and refrigerate.',
        ],
    },
    {
        title: 'Vegan Peanut Stir-Fry Noodles',
        description: 'Rice noodles tossed with crisp veg and a creamy peanut-lime sauce.',
        image: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=800&q=80',
        prepTimeMins: 15,
        cookTimeMins: 12,
        servings: 3,
        calories: 520,
        protein: 18,
        carbs: 74,
        fat: 18,
        tags: ['Vegan', 'Dinner', 'Under 30m'],
        ingredients: [
            { name: 'Rice Noodles', amount: '240', unit: 'g' },
            { name: 'Peanut Butter', amount: '3', unit: 'tbsp' },
            { name: 'Soy Sauce', amount: '3', unit: 'tbsp' },
            { name: 'Lime', amount: '1' },
            { name: 'Bell Pepper', amount: '1' },
            { name: 'Edamame', amount: '120', unit: 'g' },
        ],
        instructions: [
            'Soak or boil the rice noodles until just tender.',
            'Whisk peanut butter, soy sauce, and lime juice with a splash of water.',
            'Stir-fry the sliced pepper and edamame for 4-5 minutes.',
            'Add the noodles and the peanut sauce, tossing to coat.',
            'Serve hot, topped with crushed peanuts.',
        ],
    },
    {
        title: 'Shakshuka',
        description: 'Eggs poached in a spiced tomato and pepper sauce — a vibrant brunch favorite.',
        image: 'https://images.unsplash.com/photo-1590412200988-a436970781fa?w=800&q=80',
        prepTimeMins: 10,
        cookTimeMins: 20,
        servings: 3,
        calories: 320,
        protein: 18,
        carbs: 22,
        fat: 18,
        tags: ['Breakfast', 'Under 30m'],
        ingredients: [
            { name: 'Eggs', amount: '5' },
            { name: 'Crushed Tomatoes', amount: '400', unit: 'g' },
            { name: 'Bell Pepper', amount: '1' },
            { name: 'Onion', amount: '1' },
            { name: 'Paprika', amount: '1', unit: 'tsp' },
            { name: 'Cumin', amount: '1', unit: 'tsp' },
        ],
        instructions: [
            'Saute the diced onion and pepper until soft.',
            'Stir in the paprika and cumin, then add the tomatoes.',
            'Simmer the sauce for 8-10 minutes until thickened.',
            'Make wells and crack in the eggs.',
            'Cover and cook 5-6 minutes until the whites set.',
        ],
    },
    {
        title: 'Chicken Fajita Bowls',
        description: 'Sizzling chicken and peppers over rice with all the fajita flavor, bowl-style.',
        image: 'https://images.unsplash.com/photo-1543339308-43e59d6b73a6?w=800&q=80',
        prepTimeMins: 15,
        cookTimeMins: 15,
        servings: 4,
        calories: 540,
        protein: 44,
        carbs: 52,
        fat: 16,
        tags: ['High Protein', 'Dinner', 'Meal Prep'],
        ingredients: [
            { name: 'Chicken Breast', amount: '500', unit: 'g' },
            { name: 'Bell Peppers', amount: '2' },
            { name: 'Onion', amount: '1' },
            { name: 'Fajita Seasoning', amount: '2', unit: 'tbsp' },
            { name: 'Cooked Rice', amount: '500', unit: 'g' },
            { name: 'Lime', amount: '1' },
        ],
        instructions: [
            'Slice the chicken, peppers, and onion into strips.',
            'Toss the chicken with the fajita seasoning.',
            'Sear the chicken in a hot pan for 6-7 minutes, then set aside.',
            'Stir-fry the peppers and onion until charred at the edges.',
            'Build bowls with rice, chicken, and veg; finish with lime.',
        ],
    },
    {
        title: 'Edamame & Sea Salt Snack',
        description: 'Steamed edamame pods with flaky sea salt — a high-protein vegan snack in 8 minutes.',
        image: 'https://images.unsplash.com/photo-1564671165093-20688ff1fffa?w=800&q=80',
        prepTimeMins: 3,
        cookTimeMins: 5,
        servings: 2,
        calories: 190,
        protein: 17,
        carbs: 15,
        fat: 8,
        tags: ['Vegan', 'Snack', 'Under 30m'],
        ingredients: [
            { name: 'Edamame (in pods)', amount: '300', unit: 'g' },
            { name: 'Sea Salt', amount: '1', unit: 'tsp' },
        ],
        instructions: [
            'Bring a pot of water to a boil.',
            'Add the edamame pods and cook for 5 minutes.',
            'Drain well.',
            'Sprinkle with flaky sea salt and serve warm.',
        ],
    },
    {
        title: 'Cheesy Keto Chicken Casserole',
        description: 'A creamy, low-carb bake of chicken, broccoli, and cheddar for the whole family.',
        image: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=800&q=80',
        prepTimeMins: 15,
        cookTimeMins: 30,
        servings: 5,
        calories: 520,
        protein: 45,
        carbs: 9,
        fat: 34,
        tags: ['Keto', 'Dinner', 'Meal Prep'],
        ingredients: [
            { name: 'Cooked Chicken Breast', amount: '600', unit: 'g' },
            { name: 'Broccoli Florets', amount: '400', unit: 'g' },
            { name: 'Cream Cheese', amount: '150', unit: 'g' },
            { name: 'Cheddar Cheese', amount: '120', unit: 'g' },
            { name: 'Heavy Cream', amount: '120', unit: 'ml' },
            { name: 'Garlic', amount: '2', unit: 'cloves' },
        ],
        instructions: [
            'Preheat oven to 190C (375F).',
            'Steam the broccoli until just tender.',
            'Warm the cream cheese, heavy cream, and garlic into a smooth sauce.',
            'Combine the chicken, broccoli, and sauce in a baking dish.',
            'Top with cheddar and bake 25-30 minutes until bubbling.',
        ],
    },
    {
        title: 'Berry Chia Pudding',
        description: 'A make-ahead vegan pudding of chia seeds, almond milk, and berry compote.',
        image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800&q=80',
        prepTimeMins: 8,
        cookTimeMins: 0,
        servings: 2,
        calories: 240,
        protein: 8,
        carbs: 28,
        fat: 11,
        tags: ['Vegan', 'Breakfast', 'Meal Prep'],
        ingredients: [
            { name: 'Chia Seeds', amount: '50', unit: 'g' },
            { name: 'Almond Milk', amount: '350', unit: 'ml' },
            { name: 'Maple Syrup', amount: '1', unit: 'tbsp' },
            { name: 'Mixed Berries', amount: '100', unit: 'g' },
            { name: 'Vanilla Extract', amount: '1/2', unit: 'tsp' },
        ],
        instructions: [
            'Whisk the chia seeds, almond milk, maple syrup, and vanilla.',
            'Let it sit for 5 minutes, then whisk again to break up clumps.',
            'Cover and refrigerate for at least 4 hours or overnight.',
            'Mash half the berries into a quick compote.',
            'Layer the pudding with the compote and remaining whole berries.',
        ],
    },
    {
        title: 'Roast Beef & Horseradish Lettuce Wraps',
        description: 'Crunchy, low-carb lettuce wraps with deli roast beef and a horseradish kick.',
        image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=800&q=80',
        prepTimeMins: 10,
        cookTimeMins: 0,
        servings: 2,
        calories: 260,
        protein: 30,
        carbs: 6,
        fat: 13,
        tags: ['Keto', 'Lunch', 'Under 30m'],
        ingredients: [
            { name: 'Sliced Roast Beef', amount: '250', unit: 'g' },
            { name: 'Butter Lettuce Leaves', amount: '8' },
            { name: 'Cream Cheese', amount: '60', unit: 'g' },
            { name: 'Horseradish', amount: '1', unit: 'tbsp' },
            { name: 'Cucumber', amount: '1/2' },
        ],
        instructions: [
            'Mix the cream cheese with the horseradish.',
            'Spread the mixture onto each lettuce leaf.',
            'Lay a slice of roast beef over the top.',
            'Add a few thin cucumber sticks.',
            'Roll up the leaves and serve.',
        ],
    },
    {
        title: 'High-Protein Mac & Cheese',
        description: 'A macro-balanced mac and cheese with added cottage cheese for an extra protein boost.',
        image: 'https://images.unsplash.com/photo-1543339308-43e59d6b73a6?w=800&q=80',
        prepTimeMins: 10,
        cookTimeMins: 18,
        servings: 4,
        calories: 540,
        protein: 38,
        carbs: 58,
        fat: 16,
        tags: ['High Protein', 'Dinner', 'Meal Prep'],
        ingredients: [
            { name: 'Whole-Wheat Macaroni', amount: '300', unit: 'g' },
            { name: 'Cottage Cheese', amount: '250', unit: 'g' },
            { name: 'Cheddar Cheese', amount: '120', unit: 'g' },
            { name: 'Milk', amount: '150', unit: 'ml' },
            { name: 'Dijon Mustard', amount: '1', unit: 'tsp' },
        ],
        instructions: [
            'Cook the macaroni until al dente and drain.',
            'Blend the cottage cheese and milk until smooth.',
            'Warm the blended cheese sauce with the cheddar and mustard.',
            'Fold the pasta into the sauce until coated.',
            'Serve hot, or bake briefly for a golden top.',
        ],
    },
];

/**
 * Pure, I/O-free decision helper for the idempotent seeder.
 *
 * Given the result of a guard-by-title lookup, decide whether the upcoming
 * write is an UPDATE (a recipe with this title already exists) or a CREATE
 * (no row matched). Kept side-effect-free so it can be unit-tested directly
 * without a Prisma client or a DB connection — the seed() loop wires the real
 * I/O around it.
 */
export function planRecipeWrite(existing: { id: string } | null): 'create' | 'update' {
    return existing ? 'update' : 'create';
}

export async function seed() {
    console.log('Seeding recipes...');
    for (const recipe of MOCK_RECIPES) {
        // Guard by EXACT title (no `mode: 'insensitive'`). Recipe has no
        // @unique on `title`, so a bare `upsert` would need a migration (which
        // is user-gated). Instead we look up the existing row and branch:
        // re-running the seeder updates the matched row in place rather than
        // inserting a duplicate, so a second full pass yields zero net new rows.
        const existing = await prisma.recipe.findFirst({
            where: { title: recipe.title },
            select: { id: true },
        });

        // The write payload carries ONLY valid Recipe columns — the exact same
        // keys the original create() used (the spread of the SeedRecipe plus the
        // two JSON columns), so nothing extra is ever handed to Prisma.
        const data = {
            ...recipe,
            ingredients: recipe.ingredients,
            instructions: recipe.instructions,
        };

        if (planRecipeWrite(existing) === 'update') {
            await prisma.recipe.update({ where: { id: existing!.id }, data });
        } else {
            await prisma.recipe.create({ data });
        }
    }
    console.log('Seeding complete.');
}

// Only auto-run the seeder when this module is executed directly
// (`ts-node src/seed-recipes.ts` / `npm run seed:recipes`). Guarding the
// invocation behind `require.main === module` keeps that CLI behaviour
// byte-identical while making the module import-safe: a unit test can
// `import { MOCK_RECIPES }` to assert the data shape without triggering a live
// DB write. The seed() loop itself is unchanged.
if (require.main === module) {
    seed().catch(console.error).finally(() => prisma.$disconnect());
}
