#!/bin/bash
# One-time cleanup: untrack ~800MB of generated/binary files that were committed by mistake.
#
# What this does:
#   1. Untracks (git rm --cached) all Prisma generated DLLs, .tmp artifacts, and the
#      pandoc-*.msi installer. Files stay on disk locally — `prisma generate` will
#      recreate the generated dir per service when you run it. Other devs cloning
#      after this commit will not get the bloat.
#   2. Stages the existing .gitignore (which prevents these paths from being re-added).
#
# Run this AFTER:
#   - The bug-fix PR has merged (so its diff stays small)
#   - You're on a fresh branch off origin/main:
#       git checkout -b chore/repo-cleanup origin/main
#
# Then:
#   bash scripts/cleanup-bloat.sh
#   git push -u origin chore/repo-cleanup
#   # open a PR
#
# After this PR merges, anyone cloning the repo will get a ~30MB checkout instead
# of 800MB. CI runs and dev onboarding will be much faster.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

echo "Removing committed Prisma generated dirs across all services..."
# Each service has src/generated/prisma/* that should be regenerated, not committed.
git ls-files -- 'services/*/src/generated/' 2>/dev/null \
  | xargs -r git rm --cached -- 2>&1 \
  | tail -5 \
  || echo "  (nothing tracked under services/*/src/generated/)"

echo
echo "Removing committed Prisma temp files..."
git ls-files -- '*.tmp[0-9]*' 2>/dev/null \
  | xargs -r git rm --cached -- 2>&1 \
  | tail -5 \
  || echo "  (no *.tmp files tracked)"

echo
echo "Removing committed compiled native binaries..."
git ls-files -- '*.dll.node' 2>/dev/null \
  | xargs -r git rm --cached -- 2>&1 \
  | tail -5 \
  || echo "  (no .dll.node files tracked)"

echo
echo "Removing committed Windows MSI installers..."
git ls-files -- '*.msi' 2>/dev/null \
  | xargs -r git rm --cached -- 2>&1 \
  | tail -5 \
  || echo "  (no .msi files tracked)"

echo
echo "Removing committed log files..."
for pattern in 'turbo*.log' 'npm_install.log' 'expo_log.txt' 'tsc.log' 'tsc_output*.txt' 'val_err.txt'; do
  git ls-files -- "$pattern" 2>/dev/null \
    | xargs -r git rm --cached -- 2>&1 \
    | tail -2 \
    || true
done

echo
echo "Staging updated .gitignore..."
git add .gitignore

echo
echo "Summary of what will be committed:"
git status --short | head -20
echo "  ..."
echo "  $(git diff --cached --name-only | wc -l) files staged total"

cat <<'EOF'

Done. Review with:
  git diff --cached --stat

Commit:
  git commit -m "chore: untrack generated Prisma artifacts, native binaries, and logs

  - Add **/src/generated/, *.dll.node, *.tmp[0-9]*, *.msi to .gitignore
  - Remove ~800MB of committed bloat (auto-regenerated by prisma generate)
  - Future clones will be ~30MB instead of ~830MB"

Push and open a PR.
EOF
